### ISSUE TITLE
gifsicle:<stdin>: empty file

### ISSUE THREAD

**Issue by nicoske** [asciinema/asciicast2gif#19]
Conversion has failed. Deployed asciicast2gif from docker:

```
# docker run --rm -v $PWD:/data asciinema/asciicast2gif -t solarized-dark ibbdis.json ibbdis.gif
==> Loading ibbdis.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining screenshots into GIF file...
gifsicle:<stdin>: empty file
Killed
/app/main.js:2284
cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped=function(a){try{return cljs.core.async.impl.ioc_helpers.run_state_machine(a)}catch(b){throw b instanceof Object&&cljs.core.async.impl.ioc_helpers.aget_object(a,cljs.core.async.impl.ioc_helpers.USER_START_IDX).cljs$core$async$impl$protocols$Channel$close_BANG_$arity$1(null),b;}};
                                                                                                                                                 ^

Error: Command failed: convert -loop 0 -delay 10 /tmp/tmp.p4NraOi9Sf/0.png -delay 60 /tmp/tmp.p4NraOi9Sf/1.png -delay 6 /tmp/tmp.p4NraOi9Sf/2.png -delay 13 /tmp/tmp.p4NraOi9Sf/3.png -delay 26 /tmp/tmp.p4NraOi9Sf/4.png -delay 9 /tmp/tmp.p4NraOi9Sf/5.png -delay 10 /tmp/tmp.p4NraOi9Sf/6.png -delay 6 /tmp/tmp.p4NraOi9Sf/7.png -delay 59 /tmp/tmp.p4NraOi9Sf/8.png -delay 76 /tmp/tmp.p4NraOi9Sf/9.png -delay 13 /tmp/tmp.p4NraOi9Sf/10.png -delay 10 /tmp/tmp.p4NraOi9Sf/11.png -delay 13 /tmp/tmp.p4NraOi9Sf/12.png -delay 6 /tmp/tmp.p4NraOi9Sf/13.png -delay 23 /tmp/tmp.p4NraOi9Sf/14.png -delay 19 /tmp/tmp.p4NraOi9Sf/15.png -delay 16 /tmp/tmp.p4NraOi9Sf/16.png -delay 6 /tmp/tmp.p4NraOi9Sf/17.png -delay 73 /tmp/tmp.p4NraOi9Sf/18.png -delay 33 /tmp/tmp.p4NraOi9Sf/19.png -delay 9 /tmp/tmp.p4NraOi9Sf/20.png -delay 23 /tmp/tmp.p4NraOi9Sf/21.png -delay 16 /tmp/tmp.p4NraOi9Sf/22.png -delay 13 /tmp/tmp.p4NraOi9Sf/23.png -delay 23 /tmp/tmp.p4NraOi9Sf/24.png -delay 26 /tmp/tmp.p4NraOi9Sf/25.png -delay 6 /tmp/tmp.p4NraOi9Sf/26.png -delay 6 /tmp/tmp.p4NraOi9Sf/27.png -delay 16 /tmp/tmp.p4NraOi9Sf/28.png -delay 16 /tmp/tmp.p4NraOi9Sf/29.png -delay 33 /tmp/tmp.p4NraOi9Sf/30.png -delay 30 /tmp/tmp.p4NraOi9Sf/31.png -delay 19 /tmp/tmp.p4NraOi9Sf/32.png -delay 50 /tmp/tmp.p4NraOi9Sf/33.png -delay 46 /tmp/tmp.p4NraOi9Sf/34.png -delay 50 /tmp/tmp.p4NraOi9Sf/35.png -delay 46 /tmp/tmp.p4NraOi9Sf/36.png -delay 66 /tmp/tmp.p4NraOi9Sf/37.png -delay 53 /tmp/tmp.p4NraOi9Sf/38.png -delay 53 /tmp/tmp.p4NraOi9Sf/39.png -delay 59 /tmp/tmp.p4NraOi9Sf/40.png -delay 50 /tmp/tmp.p4NraOi9Sf/41.png -delay 36 /tmp/tmp.p4NraOi9Sf/42.png -delay 19 /tmp/tmp.p4NraOi9Sf/43.png -delay 53 /tmp/tmp.p4NraOi9Sf/44.png -delay 40 /tmp/tmp.p4NraOi9Sf/45.png -delay 16 /tmp/tmp.p4NraOi9Sf/46.png -delay 19 /tmp/tmp.p4NraOi9Sf/47.png -delay 36 /tmp/tmp.p4NraOi9Sf/48.png -delay 33 /tmp/tmp.p4NraOi9Sf/49.png -delay 46 /tmp/tmp.p4NraOi9Sf/50.png -delay 13 /tmp/tmp.p4NraOi9Sf/51.png -delay 13 /tmp/tmp.p4NraOi9Sf/52.png -delay 53 /tmp/tmp.p4NraOi9Sf/53.png -delay 6 /tmp/tmp.p4NraOi9Sf/54.png -delay 80 /tmp/tmp.p4NraOi9Sf/55.png -delay 150 /tmp/tmp.p4NraOi9Sf/56.png -delay 193 /tmp/tmp.p4NraOi9Sf/57.png -delay 106 /tmp/tmp.p4NraOi9Sf/58.png -delay 43 /tmp/tmp.p4NraOi9Sf/59.png -delay 319 /tmp/tmp.p4NraOi9Sf/60.png -delay 3 /tmp/tmp.p4NraOi9Sf/61.png -delay 3 /tmp/tmp.p4NraOi9Sf/62.png -delay 96 /tmp/tmp.p4NraOi9Sf/63.png -delay 193 /tmp/tmp.p4NraOi9Sf/64.png -delay 276 /tmp/tmp.p4NraOi9Sf/65.png -delay 86 /tmp/tmp.p4NraOi9Sf/66.png -delay 66 /tmp/tmp.p4NraOi9Sf/67.png -delay 63 /tmp/tmp.p4NraOi9Sf/68.png -delay 63 /tmp/tmp.p4NraOi9Sf/69.png -delay 60 /tmp/tmp.p4NraOi9Sf/70.png -delay 76 /tmp/tmp.p4NraOi9Sf/71.png -delay 60 /tmp/tmp.p4NraOi9Sf/72.png -delay 66 /tmp/tmp.p4NraOi9Sf/73.png -delay 60 /tmp/tmp.p4NraOi9Sf/74.png -delay 60 /tmp/tmp.p4NraOi9Sf/75.png -delay 3 /tmp/tmp.p4NraOi9Sf/76.png -delay 126 /tmp/tmp.p4NraOi9Sf/77.png -delay 110 /tmp/tmp.p4NraOi9Sf/78.png -delay 200 /tmp/tmp.p4NraOi9Sf/79.png -delay 146 /tmp/tmp.p4NraOi9Sf/80.png -delay 193 /tmp/tmp.p4NraOi9Sf/81.png -delay 1556 /tmp/tmp.p4NraOi9Sf/82.png -delay 63 /tmp/tmp.p4NraOi9Sf/83.png -delay 123 /tmp/tmp.p4NraOi9Sf/84.png -delay 3 /tmp/tmp.p4NraOi9Sf/85.png -delay 93 /tmp/tmp.p4NraOi9Sf/86.png -delay 96 /tmp/tmp.p4NraOi9Sf/87.png -delay 93 /tmp/tmp.p4NraOi9Sf/88.png -delay 133 /tmp/tmp.p4NraOi9Sf/89.png -delay 5030 /tmp/tmp.p4NraOi9Sf/90.png -delay 3 /tmp/tmp.p4NraOi9Sf/91.png -delay 223 /tmp/tmp.p4NraOi9Sf/92.png -delay 293 /tmp/tmp.p4NraOi9Sf/93.png -delay 223 /tmp/tmp.p4NraOi9Sf/94.png -delay 3 /tmp/tmp.p4NraOi9Sf/95.png -delay 3 /tmp/tmp.p4NraOi9Sf/96.png -delay 3 /tmp/tmp.p4NraOi9Sf/97.png -delay 140 /tmp/tmp.p4NraOi9Sf/98.png -delay 156 /tmp/tmp.p4NraOi9Sf/99.png -delay 836 /tmp/tmp.p4NraOi9Sf/100.png -delay 216 /tmp/tmp.p4NraOi9Sf/101.png -delay 3 /tmp/tmp.p4NraOi9Sf/102.png -delay 3 /tmp/tmp.p4NraOi9Sf/103.png -delay 230 /tmp/tmp.p4NraOi9Sf/104.png -delay 213 /tmp/tmp.p4NraOi9Sf/105.png -delay 106 /tmp/tmp.p4NraOi9Sf/106.png -delay 96 /tmp/tmp.p4NraOi9Sf/107.png -delay 73 /tmp/tmp.p4NraOi9Sf/108.png -delay 4796 /tmp/tmp.p4NraOi9Sf/109.png -delay 233 /tmp/tmp.p4NraOi9Sf/110.png -delay 436 /tmp/tmp.p4NraOi9Sf/111.png -delay 26526 /tmp/tmp.p4NraOi9Sf/112.png -delay 69 /tmp/tmp.p4NraOi9Sf/113.png -delay 60 /tmp/tmp.p4NraOi9Sf/114.png -delay 63 /tmp/tmp.p4NraOi9Sf/115.png -delay 66 /tmp/tmp.p4NraOi9Sf/116.png -delay 63 /tmp/tmp.p4NraOi9Sf/117.png -delay 3 /tmp/tmp.p4NraOi9Sf/118.png -delay 133 /tmp/tmp.p4NraOi9Sf/119.png -delay 96 /tmp/tmp.p4NraOi9Sf/120.png -delay 73 /tmp/tmp.p4NraOi9Sf/121.png -delay 73 /tmp/tmp.p4NraOi9Sf/122.png -delay 216 /tmp/tmp.p4NraOi9Sf/123.png -delay 63 /tmp/tmp.p4NraOi9Sf/124.png -delay 126 /tmp/tmp.p4NraOi9Sf/125.png -delay 3 /tmp/tmp.p4NraOi9Sf/126.png -delay 3 /tmp/tmp.p4NraOi9Sf/127.png -delay 3 /tmp/tmp.p4NraOi9Sf/128.png -delay 3 /tmp/tmp.p4NraOi9Sf/129.png -delay 3 /tmp/tmp.p4NraOi9Sf/130.png -delay 3 /tmp/tmp.p4NraOi9Sf/131.png -delay 233 /tmp/tmp.p4NraOi9Sf/132.png -delay 230 /tmp/tmp.p4NraOi9Sf/133.png -delay 3 /tmp/tmp.p4NraOi9Sf/134.png -delay 3 /tmp/tmp.p4NraOi9Sf/135.png -delay 3 /tmp/tmp.p4NraOi9Sf/136.png -delay 3 /tmp/tmp.p4NraOi9Sf/137.png -delay 69 /tmp/tmp.p4NraOi9Sf/138.png -delay 3 /tmp/tmp.p4NraOi9Sf/139.png -delay 63 /tmp/tmp.p4NraOi9Sf/140.png -delay 200 /tmp/tmp.p4NraOi9Sf/141.png -delay 3 /tmp/tmp.p4NraOi9Sf/142.png -delay 3 /tmp/tmp.p4NraOi9Sf/143.png -delay 73 /tmp/tmp.p4NraOi9Sf/144.png -delay 216 /tmp/tmp.p4NraOi9Sf/145.png -delay 73 /tmp/tmp.p4NraOi9Sf/146.png -delay 156 /tmp/tmp.p4NraOi9Sf/147.png -delay 3046 /tmp/tmp.p4NraOi9Sf/148.png -delay 3 /tmp/tmp.p4NraOi9Sf/149.png -delay 123 /tmp/tmp.p4NraOi9Sf/150.png -delay 76 /tmp/tmp.p4NraOi9Sf/151.png -delay 73 /tmp/tmp.p4NraOi9Sf/152.png -delay 246 /tmp/tmp.p4NraOi9Sf/153.png -delay 800 /tmp/tmp.p4NraOi9Sf/154.png -delay 79 /tmp/tmp.p4NraOi9Sf/155.png -delay 80 /tmp/tmp.p4NraOi9Sf/156.png -delay 3 /tmp/tmp.p4NraOi9Sf/157.png -delay 100 /tmp/tmp.p4NraOi9Sf/158.png -layers Optimize gif:- | gifsicle -k 32 -O2 -Okeep-empty -o ibbdis.gif -
gifsicle:<stdin>: empty file
Killed

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.asciinema.gif.main.shell (/app/main.js:5245:143)
    at Object.asciinema.gif.main.gen_gif (/app/main.js:5252:371)
    at /app/main.js:5261:136
    at d (/app/main.js:5255:185)
    at b (/app/main.js:5256:17)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine (/app/main.js:2283:287)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped (/app/main.js:2284:116)
    at /app/main.js:2285:321
#

```

**Comment by nicoske** [comment]
my mistake, path was not mounted

**Comment by nicolasbock** [comment]
I am getting the same error message. Could you elaborate on what you mean with "path was not mounted"?
