### ISSUE TITLE
Running via Docker image fails: Unexpected token in JSON at positon 0

### ISSUE THREAD

**Issue by christopher-dG** [asciinema/asciicast2gif#21]
I downloaded the file and found a regular curly brace at position 0.

```
[ ~ ] docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/bqBwff05mI7Cl9bz7EqLPMKF8.json demo.gif                                                                                                                                   [ master ]
==> Loading https://asciinema.org/a/bqBwff05mI7Cl9bz7EqLPMKF8.json...
/app/main.js:2284
cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped=function(a){try{return cljs.core.async.impl.ioc_helpers.run_state_machine(a)}catch(b){throw b instanceof Object&&cljs.core.async.impl.ioc_helpers.aget_object(a,cljs.core.async.impl.ioc_helpers.USER_START_IDX).cljs$core$async$impl$protocols$Channel$close_BANG_$arity$1(null),b;}};
                                                                                                                                                 ^

SyntaxError: Unexpected token  in JSON at position 0
    at parse (native)
    at asciinema.gif.main.parse_json (/app/main.js:5235:406)
    at Function.e [as cljs$core$IFn$_invoke$arity$1] (/app/main.js:931:362)
    at /app/main.js:2620:464
    at Function.f [as cljs$core$IFn$_invoke$arity$2] (/app/main.js:1065:400)
    at Function.g [as cljs$core$IFn$_invoke$arity$2] (/app/main.js:2276:3)
    at cljs.core.async.impl.channels.ManyToManyChannel.cljs$core$async$impl$protocols$WritePort$put_BANG_$arity$3 (/app/main.js:2257:80)
    at Object.cljs.core.async.impl.protocols.put_BANG_ (/app/main.js:2171:146)
    at Function.cljs.core.async.put_BANG_.cljs$core$IFn$_invoke$arity$2 (/app/main.js:2359:176)
    at IncomingMessage.<anonymous> (/app/main.js:5238:483)

[ ~ ] docker -v
Docker version 17.06.1-ce, build 874a7374f3
```

**Comment by sickill** [comment]
Yeah, it seems 302 redirects are not handled properly here.

**Comment by sickill** [comment]
This was actually a lack of `Content-Encoding: gzip` support. Anyway, it seems to be working now.
