### ISSUE TITLE
Fails to build ClojureScript code

### ISSUE THREAD

**Issue by arximboldi** [asciinema/asciicast2gif#22]
When running `lein cljsbuild once main` I get the following error. Using the Docker image is failing too because of #21 😢 

```
Compiling ClojureScript...
Compiling "main.js" from ["src"]...
Compiling "main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:/home/raskolnikov/soft/asciicast2gif/src/asciinema/gif/main.cljs {:file #object[java.io.File 0x3d41449a "/home/raskolnikov/soft/asciicast2gif/src/asciinema/gif/main.cljs"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at cljs.compiler$compile_file$fn__3884.invoke(compiler.cljc:1471)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1436)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1412)
	at cljs.closure$compile_file.invokeStatic(closure.clj:497)
	at cljs.closure$compile_file.invoke(closure.clj:488)
	at cljs.closure$eval5698$fn__5699.invoke(closure.clj:566)
	at cljs.closure$eval5634$fn__5635$G__5623__5642.invoke(closure.clj:450)
	at cljs.closure$compile_sources$iter__5834__5838$fn__5839.invoke(closure.clj:914)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3033)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:908)
	at cljs.closure$compile_sources.invoke(closure.clj:897)
	at cljs.closure$build.invokeStatic(closure.clj:2307)
	at cljs.closure$build.invoke(closure.clj:2236)
	at cljs.build.api$build.invokeStatic(api.clj:202)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljs.build.api$build.invokeStatic(api.clj:192)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljsbuild.compiler$compile_cljs$fn__6943.invoke(compiler.clj:66)
	at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:65)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:54)
	at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:165)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:126)
	at user$eval7047$iter__7083__7087$fn__7088$fn__7106.invoke(form-init545893261685407571.clj:1)
	at user$eval7047$iter__7083__7087$fn__7088.invoke(form-init545893261685407571.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3024)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at user$eval7047.invokeStatic(form-init545893261685407571.clj:1)
	at user$eval7047.invoke(form-init545893261685407571.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: asciinema.player.source, could not locate asciinema/player/source.cljs, asciinema/player/source.cljc, or Closure namespace "asciinema.player.source" in file /home/raskolnikov/soft/asciicast2gif/src/asciinema/gif/main.cljs {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:657)
	at cljs.analyzer$error.invoke(analyzer.cljc:653)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:655)
	at cljs.analyzer$error.invoke(analyzer.cljc:653)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:1975)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1951)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3238)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3233)
	at cljs.analyzer$analyze_STAR_$fn__2767.invoke(analyzer.cljc:3328)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3328)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3318)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3352)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3335)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1307)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1287)
	at cljs.compiler$compile_file_STAR_$fn__3861.invoke(compiler.cljc:1381)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1206)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1195)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1370)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1363)
	at cljs.compiler$compile_file$fn__3884.invoke(compiler.cljc:1459)
	... 56 more
Subprocess failed
```

**Comment by arximboldi** [comment]
```
$ lein --version
Leiningen 2.7.1 on Java 1.8.0_141 OpenJDK 64-Bit Server VM
```

**Comment by jimhester** [comment]
I ran into the same issue. The problem is the asciicinema-player is a submodule, and you did not retrieve it. Run the following in the root of the project, then you should be able to build correctly.

```shell
git submodule init && git submodule update
```

**Comment by arximboldi** [comment]
Oh stupid me, thank you!
