### ISSUE TITLE
Docker command asciicast2gif not work

### ISSUE THREAD

**Issue by rockagen** [asciinema/asciicast2gif#46]
I use docker image run this command,output:
``` bash
ra@17zy:~/Downloads/video$ sudo asciicast2gif https://asciinema.org/a/118274.json demo.gif
==> Loading https://asciinema.org/a/118274.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Couldn't get geometry of requested DOM element
/usr/local/lib/node_modules/asciicast2gif/main.js:696
return new Zo(a,Qe)}function ap(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Uo(a[6]),b;throw c;}}function bp(a,b,c){c=Vo(c,$o(function(c){a[2]=c;a[1]=b;return ap(a)}));return r(c)?(a[2]=Ob(c),a[1]=b,bj):null}function cp(a,b){a=a[6];null!=b&&a.Dc(null,b,$o(function(){return function(){return null}}(a)));Uo(a);return a}
                                                                                                                   ^

Error: program exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/asciicast2gif/main.js:704:399)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

node: v8.10.0
npm: 3.5.2
system: Linux 17zy 4.15.0-29-generic #31-Ubuntu x86_64 x86_64 GNU/Linux
docker: Docker version 17.06.2-ce, build a04f55b
docker-image: asciinema/asciicast2gif   latest      54698cc15d97

**Comment by rockagen** [comment]
it's worked,closed
