### ISSUE TITLE
Object has no method 'execSync'

### ISSUE THREAD

**Issue by rokhimin** [asciinema/asciicast2gif#70]
I have error

```
root@goorm:/workspace/whdzera(master)# asciicast2gif https://asciinema.org/a/266267.cast demo.gif
==> Loading https://asciinema.org/a/266267.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 42 screenshots into GIF file...

/usr/local/lib/node_modules/asciicast2gif/main.js:697
):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;
                                                                    ^
TypeError: Object #<Object> has no method 'execSync'
    at Dp (/usr/local/lib/node_modules/asciicast2gif/main.js:708:246)
    at /usr/local/lib/node_modules/asciicast2gif/main.js:713:178
    at Function.b (/usr/local/lib/node_modules/asciicast2gif/main.js:709:287)
    at ep (/usr/local/lib/node_modules/asciicast2gif/main.js:697:48)
    at /usr/local/lib/node_modules/asciicast2gif/main.js:697:193
    at /usr/local/lib/node_modules/asciicast2gif/main.js:689:264
    at Object.Po [as _onImmediate] (/usr/local/lib/node_modules/asciicast2gif/main.js:685:331)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

what happen?

**Comment by geekyouth** [comment]
me too

```sh
/usr/lib/node_modules/asciicast2gif/main.js:697
):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;
                                                                    ^
TypeError: Object #<Object> has no method 'execSync'
    at Dp (/usr/lib/node_modules/asciicast2gif/main.js:708:246)
    at /usr/lib/node_modules/asciicast2gif/main.js:713:178
    at Function.b (/usr/lib/node_modules/asciicast2gif/main.js:709:287)
    at ep (/usr/lib/node_modules/asciicast2gif/main.js:697:48)
    at /usr/lib/node_modules/asciicast2gif/main.js:697:193
    at /usr/lib/node_modules/asciicast2gif/main.js:689:264
    at Object.Po [as _onImmediate] (/usr/lib/node_modules/asciicast2gif/main.js:685:331)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

```

**Comment by ku1ik** [comment]
Not sure what's up here, I guess some Node version related problem...
Either way, please try https://github.com/asciinema/agg instead, which is a successor to asciicast2gif.
