### ISSUE TITLE
Fails with ERR_STREAM_DESTROYED

### ISSUE THREAD

**Issue by dbarnett** [asciinema/asciicast2gif#75]
When I try to run asciicast2gif on my cast file from https://asciinema.org/a/316688, it always fails with an ugly uncaught ERR_STREAM_DESTROYED error:
```
$ asciicast2gif 316688.cast vroom_cast.gif
==> Loading 316688.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:697
Qe)}function ep(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;}}function fp(a,b,c){c=Zo(c,dp(function(c){a[2]=c;a[1]=b;return ep(a)}));return r(c)?(a[2]=Nb(c),a[1]=b,dj):null}function gp(a,b){a=a[6];null!=b&&a.Dc(null,b,dp(function(){return function(){return null}}(a)));Yo(a);return a}
                                                                                                   ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at Socket.Writable.write (_stream_writable.js:288:11)
    at of (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:706:308)
    at Function.e [as c] (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:293:156)
    at /home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:295:256
    at /home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:295:280
    at ue (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:243:437)
    at te.f.P (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:246:266)
    at w (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:172:83)
    at Hh (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:485:308)
    at Ap (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:706:423)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at Socket.Writable.write (_stream_writable.js:310:5)
    at of (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:706:308)
    [... lines matching original stack trace ...]
    at Hh (/home/dbarnett/.npm-global/lib/node_modules/asciicast2gif/main.js:485:308) {
  code: 'ERR_STREAM_DESTROYED'
}
```

**Comment by ku1ik** [comment]
Not sure what's the problem here. Either way you should try https://github.com/asciinema/agg instead, which is a successor to asciicast2gif.

I generated gif from your recording with `agg` just fine:

![316688](https://user-images.githubusercontent.com/17589/184545842-3530a545-c22e-424f-8d77-163decb792c8.gif)
