### ISSUE TITLE
[bug] Error: certificate has expired

### ISSUE THREAD

**Issue by geekyouth** [asciinema/asciicast2gif#83]
```shell
[root@SZ gif]# docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/XFTSQAeaffrg7XSDuyK1Hdr8x.cast?dl=1 sz-1.gif
==> Loading https://asciinema.org/a/XFTSQAeaffrg7XSDuyK1Hdr8x.cast?dl=1...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)
[root@SZ gif]# export http_proxy=http://192.168.8.12:1080
[root@SZ gif]# export https_proxy=http://192.168.8.12:1080
[root@SZ gif]# docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/XFTSQAeaffrg7XSDuyK1Hdr8x.cast?dl=1 sz-1.gif
==> Loading https://asciinema.org/a/XFTSQAeaffrg7XSDuyK1Hdr8x.cast?dl=1...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)
[root@SZ gif]#

```

**Comment by mathieu-aubin** [comment]
@sickill verified on a fresh pull

**Comment by mathieu-aubin** [comment]
Works as a workaround but ultimately, building a new image with a more recent Nodejs version (image has node 6.x installed) would make more sense.

But hey - works, so...

**Comment by ku1ik** [comment]
I don't have bandwidth to fix this. Also this tool has been superceded by [agg](https://github.com/asciinema/agg) anyway. For now I suggest `wget <url>` + `agg`/ `asciicast2gif` combo.
