### ISSUE TITLE
asciinema2gif: convert-im6.q16: cache resources exhausted

### ISSUE THREAD

**Issue by Sas2k** [asciinema/asciicast2gif#89]
hello, I was a simply trying to convert and asciinema to gif but this error was produced.
```bash
==> Loading https://asciinema.org/a/QrrLJy3v0VQBWa22uxCRQMOQM.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 76 screenshots into GIF file...
convert-im6.q16: cache resources exhausted `/tmp/tmp.BeaYNX4ceS/0.png' @ error/cache.c/OpenPixelCache/4083.
gifsicle:<stdin>:#0: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#1: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#2: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#3: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#4: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#5: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#6: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#7: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#8: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#9: read error: missing 3073895 pixels of image data
gifsicle: (plus more errors; is this GIF corrupt?)
gifsicle: warning: trivial adaptive palette (only 1 colors in source)
/home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:697
Qe)}function ep(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;}}function fp(a,b,c){c=Zo(c,dp(function(c){a[2]=c;a[1]=b;return ep(a)}));return r(c)?(a[2]=Nb(c),a[1]=b,dj):null}function gp(a,b){a=a[6];null!=b&&a.Dc(null,b,dp(function(){return function(){return null}}(a)));Yo(a);return a}
                                                                                                   ^

Error: Command failed: convert -loop 0 -delay 26 /tmp/tmp.BeaYNX4ceS/0.png -delay 213 /tmp/tmp.BeaYNX4ceS/1.png -delay 46 /tmp/tmp.BeaYNX4ceS/2.png -delay 146 /tmp/tmp.BeaYNX4ceS/3.png -delay 120 /tmp/tmp.BeaYNX4ceS/4.png -delay 20 /tmp/tmp.BeaYNX4ceS/5.png -delay 46 /tmp/tmp.BeaYNX4ceS/6.png -delay 59 /tmp/tmp.BeaYNX4ceS/7.png -delay 20 /tmp/tmp.BeaYNX4ceS/8.png -delay 13 /tmp/tmp.BeaYNX4ceS/9.png -delay 73 /tmp/tmp.BeaYNX4ceS/10.png -delay 26 /tmp/tmp.BeaYNX4ceS/11.png -delay 26 /tmp/tmp.BeaYNX4ceS/12.png -delay 13 /tmp/tmp.BeaYNX4ceS/13.png -delay 13 /tmp/tmp.BeaYNX4ceS/14.png -delay 13 /tmp/tmp.BeaYNX4ceS/15.png -delay 73 /tmp/tmp.BeaYNX4ceS/16.png -delay 26 /tmp/tmp.BeaYNX4ceS/17.png -delay 13 /tmp/tmp.BeaYNX4ceS/18.png -delay 26 /tmp/tmp.BeaYNX4ceS/19.png -delay 33 /tmp/tmp.BeaYNX4ceS/20.png -delay 46 /tmp/tmp.BeaYNX4ceS/21.png -delay 26 /tmp/tmp.BeaYNX4ceS/22.png -delay 13 /tmp/tmp.BeaYNX4ceS/23.png -delay 33 /tmp/tmp.BeaYNX4ceS/24.png -delay 20 /tmp/tmp.BeaYNX4ceS/25.png -delay 53 /tmp/tmp.BeaYNX4ceS/26.png -delay 26 /tmp/tmp.BeaYNX4ceS/27.png -delay 13 
/tmp/tmp.BeaYNX4ceS/28.png -delay 279 /tmp/tmp.BeaYNX4ceS/29.png -delay 13 /tmp/tmp.BeaYNX4ceS/30.png -delay 13 /tmp/tmp.BeaYNX4ceS/31.png -delay 26 /tmp/tmp.BeaYNX4ceS/32.png -delay 46 /tmp/tmp.BeaYNX4ceS/33.png -delay 19 /tmp/tmp.BeaYNX4ceS/34.png -delay 19 /tmp/tmp.BeaYNX4ceS/35.png -delay 26 /tmp/tmp.BeaYNX4ceS/36.png -delay 13 /tmp/tmp.BeaYNX4ceS/37.png -delay 53 /tmp/tmp.BeaYNX4ceS/38.png -delay 19 /tmp/tmp.BeaYNX4ceS/39.png -delay 26 /tmp/tmp.BeaYNX4ceS/40.png -delay 6 /tmp/tmp.BeaYNX4ceS/41.png -delay 20 /tmp/tmp.BeaYNX4ceS/42.png -delay 19 /tmp/tmp.BeaYNX4ceS/43.png -delay 53 /tmp/tmp.BeaYNX4ceS/44.png -delay 26 /tmp/tmp.BeaYNX4ceS/45.png -delay 26 /tmp/tmp.BeaYNX4ceS/46.png -delay 19 /tmp/tmp.BeaYNX4ceS/47.png -delay 26 /tmp/tmp.BeaYNX4ceS/48.png -delay 20 /tmp/tmp.BeaYNX4ceS/49.png -delay 13 /tmp/tmp.BeaYNX4ceS/50.png -delay 13 /tmp/tmp.BeaYNX4ceS/51.png -delay 6 /tmp/tmp.BeaYNX4ceS/52.png -delay 39 
/tmp/tmp.BeaYNX4ceS/53.png -delay 26 /tmp/tmp.BeaYNX4ceS/54.png -delay 13 /tmp/tmp.BeaYNX4ceS/55.png -delay 6 /tmp/tmp.BeaYNX4ceS/56.png -delay 73 /tmp/tmp.BeaYNX4ceS/57.png -delay 73 /tmp/tmp.BeaYNX4ceS/58.png -delay 19 /tmp/tmp.BeaYNX4ceS/59.png -delay 13 /tmp/tmp.BeaYNX4ceS/60.png -delay 26 /tmp/tmp.BeaYNX4ceS/61.png -delay 26 /tmp/tmp.BeaYNX4ceS/62.png -delay 73 /tmp/tmp.BeaYNX4ceS/63.png -delay 73 /tmp/tmp.BeaYNX4ceS/64.png -delay 26 /tmp/tmp.BeaYNX4ceS/65.png -delay 13 /tmp/tmp.BeaYNX4ceS/66.png -delay 60 /tmp/tmp.BeaYNX4ceS/67.png -delay 286 /tmp/tmp.BeaYNX4ceS/68.png -delay 13 /tmp/tmp.BeaYNX4ceS/69.png -delay 773 /tmp/tmp.BeaYNX4ceS/70.png -delay 26 /tmp/tmp.BeaYNX4ceS/71.png -delay 46 /tmp/tmp.BeaYNX4ceS/72.png -delay 13 /tmp/tmp.BeaYNX4ceS/73.png -delay 93 /tmp/tmp.BeaYNX4ceS/74.png -delay 100 /tmp/tmp.BeaYNX4ceS/75.png -layers Optimize gif:- | gifsicle -k 64 -O2 -Okeep-empty --lossy=80 -o demo.gif -convert-im6.q16: cache resources exhausted `/tmp/tmp.BeaYNX4ceS/0.png' @ error/cache.c/OpenPixelCache/4083.
gifsicle:<stdin>:#0: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#1: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#2: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#3: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#4: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#5: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#6: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#7: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#8: read error: missing 3073895 pixels of image data
gifsicle:<stdin>:#9: read error: missing 3073895 pixels of image data
gifsicle: (plus more errors; is this GIF corrupt?)
gifsicle: warning: trivial adaptive palette (only 1 colors in source)

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Dp (/home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:708:246)
    at /home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:713:178
    at Function.b [as h] (/home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:709:287)
    at ep (/home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:697:48)
    at /home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:697:193
    at /home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:689:264
    at Immediate.Po (/home/sasenp/.nvm/versions/node/v17.2.0/lib/node_modules/asciicast2gif/main.js:685:331)
    at processImmediate (node:internal/timers:464:21) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(929) [Uint8Array] [
       99, 111, 110, 118, 101, 114, 116,  45, 105, 109,  54,  46,
      113,  49,  54,  58,  32,  99,  97,  99, 104, 101,  32, 114,
      101, 115, 111, 117, 114,  99, 101, 115,  32, 101, 120, 104,
       97, 117, 115, 116, 101, 100,  32,  96,  47, 116, 109, 112,
       47, 116, 109, 112,  46,  66, 101,  97,  89,  78,  88,  52,
       99, 101,  83,  47,  48,  46, 112, 110, 103,  39,  32,  64,
       32, 101, 114, 114, 111, 114,  47,  99,  97,  99, 104, 101,
       46,  99,  47,  79, 112, 101, 110,  80, 105, 120, 101, 108,
       67,  97,  99, 104,
      ... 829 more items
    ]
  ],
  pid: 9185,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(929) [Uint8Array] [
     99, 111, 110, 118, 101, 114, 116,  45, 105, 109,  54,  46,
    113,  49,  54,  58,  32,  99,  97,  99, 104, 101,  32, 114,
    101, 115, 111, 117, 114,  99, 101, 115,  32, 101, 120, 104,
     97, 117, 115, 116, 101, 100,  32,  96,  47, 116, 109, 112,
     47, 116, 109, 112,  46,  66, 101,  97,  89,  78,  88,  52,
     99, 101,  83,  47,  48,  46, 112, 110, 103,  39,  32,  64,
     32, 101, 114, 114, 111, 114,  47,  99,  97,  99, 104, 101,
     46,  99,  47,  79, 112, 101, 110,  80, 105, 120, 101, 108,
     67,  97,  99, 104,
    ... 829 more items
  ]
}

Node.js v17.2.0
```

**Comment by ku1ik** [comment]
Your recording is no longer available (has been archived) so can't reproduce.
In the future use [agg](https://github.com/asciinema/agg) instead.
